script: 'ci/travis.rb'
rvm:
  - 1.9.2
  - 1.9.3
  - jruby
env:
  - WATCH_TOWER_ENV=test JRUBY_OPTS="${JRUBY_OPTS} --1.9" ADAPTER="mysql"
  - WATCH_TOWER_ENV=test JRUBY_OPTS="${JRUBY_OPTS} --1.9" ADAPTER="postgresql"
notifications:
  recipients:
    - wael.nasreddine@gmail.com